name: Deploy to AWS (CDK)

on:
  push:
    branches:
      - main

    name: Build App
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}  
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
      AWS_CF_DOMAIN: '${{ secrets.AWS_CF_DOMAIN }}'
      NODE_VERSION: 20.x
    strategy:
      matrix:
        python-version:
          - 3.9

    steps:
      - name: Missing AWS Credentials
        if: ${{ !env.AWS_SECRET_KEY || !env.AWS_ACCESS_KEY }}
        run: exit 1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # npm install -g aws-cdk
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "us-east-1"
      - name: Deploy to AWS
        run: aws-cdk deploy --app="python3 ${PWD}/cdk/ai-rag/app.py" --require-approval=never
      - name: Destroy stack
        run: aws-cdk destroy --app="python3 ${PWD}/cdk/ai-rag/app.py" --force