service: serverless-lambda-python

provider:
  name: aws
  runtime: python3.9
  stage: prod
  region: us-east-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: handle_embedding
    handler: lambda.handle_embedding
    description: creates embedding from documents
    timeout: 60 # seconds
    memorySize: 256 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
